development:
  adapter: postgresql
  encoding: unicode
  database: vibraction_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: vibraction_test
  pool: 5
  username:
  password:
  host: localhost

